searchSpaceFile: gnn_search_space.json
trialCommand: python3 main_explainer.py --train --explain --dataset_path=/home/src/datasets/ --dataset_name=Schiza
experimentWorkingDirectory: ./IBGNN/
trialGpuNumber: 0
trialConcurrency: 4
maxTrialNumber: 20
tuner:
  name: TPE
  classArgs:
    optimize_mode: maximize
trainingService:
  platform: local
